./Examples/Monocular/eutech_imu_2 inputFiles1.yaml
./Examples/Monocular/eutech_imu_2 inputFiles2.yaml
./Examples/Monocular/eutech_imu_2 inputFiles3.yaml
./Examples/Monocular/eutech_imu_2 inputFiles4.yaml
./Examples/Monocular/eutech_imu_2 inputFiles5.yaml
./Examples/Monocular/eutech_imu_2 inputFiles6.yaml
./Examples/Monocular/eutech_imu_2 inputFiles7.yaml
./Examples/Monocular/eutech_imu_2 inputFiles8.yaml
./Examples/Monocular/eutech_imu_2 inputFiles9.yaml
./Examples/Monocular/eutech_imu_2 inputFiles10.yaml
./Examples/Monocular/eutech_imu_2 inputFiles11.yaml
./Examples/Monocular/eutech_imu_2 inputFiles12.yaml
