%YAML:1.0

# Path to save tmp files/results
test.InitVIOTmpPath: "/home/aayush/workspace/sandbox/VIROB/tmp/"

test.DiscardTime: 0

#bagfile (not used in eutech mode, but can be switched optionally with correct version of SLAM)
bagfile: "/home/aayush/workspace/sandbox/VIROB/V1_02_medium.bag"

#######################################

imutopic: "/imu0"
imagetopic: "/cam0/image_raw"


# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
 [-0.024682, 0.990875, -0.132501, 0.041862302,
  -0.084069, 0.130015, 0.987942, -0.15906197,
  0.996154, 0.035524, 0.080092, -0.15419175,
  0.0, 0.0, 0.0, 1.0]

# Local Window size
LocalMapping.LocalWindowSize: 5

OutputFolder: "/home/aayush/workspace/sandbox/VIROB/tmp/"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Should be adjusted according to camera module and video settings
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 757.450897273
Camera.fy: 759.756884175
Camera.cx: 613.7086584682
Camera.cy: 333.0210952713

Camera.k1: -0.368530299792
Camera.k2: 0.178960158484
Camera.p1: -0.001378795654
Camera.p2: 0.000578185279
Camera.k3: -0.0497533036

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 10.0

# IR projector baseline times fx (aprox.)
Camera.bf: 10.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 8000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid 
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast   
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

